environment:
  name: harnessdevenvdep
  identifier: harnessdevenvdep
  tags: {}
  type: PreProduction
  orgIdentifier: default
  projectIdentifier: default_project
  variables:
    - name: TEST_URL
      type: String
      value: http://test.com.ar
      description: ""
      required: false
